sudo: required

language: php

php:
  - 5.5
  - 5.6
  - 7

services:
    - docker

branches:
    only:
        - master

before_install:
    - docker run -d -p "127.0.0.1:9200:9200" elasticsearch

install:
    - composer install --prefer-source

before_script:
    - composer self-update

script:
    - php bin/phpunit
